### ISSUE TITLE
band_select函数未被定义

### ISSUE THREAD

**Issue by mingze-great** [ZhaoxuLi123/AETNet#2]
![Snipaste_2024-08-17_15-24-42](https://github.com/user-attachments/assets/d1c7b22d-461f-452f-b6d2-376a6f539204)
这个地方报下面这个错误怎么回事
![Snipaste_2024-08-17_15-33-36](https://github.com/user-attachments/assets/1eddf12a-41fe-4ba2-90cc-9068c56f3c30)

**Comment by ZhaoxuLi123** [comment]
添加下面函数定义即可
def band_select(sensor):
    if sensor == 'aviris_ng':
        good_bands = np.r_[15:109, 118:145, 158:187, 227:274, 328:407]
        color_bands = [53, 35, 19]
    elif sensor == 'aviris':
        good_bands = np.r_[7:57, 65:79, 85:104, 122:149, 172:224]
        color_bands = [28, 19, 11]
    return good_bands, color_bands
提供的代码是有这个函数的，是不是误删了。
